import nibabel as nib
import numpy as np
import trimesh
import os
import sys
import argparse # 导入 argparse

# ===================== 函数定义 (保持与原始脚本一致) =====================

# read_surface 函数 ... (与您提供的原始脚本完全一致) ...
def read_surface(surface_path):
    print(f"尝试加载表面文件: {surface_path}")
    if not os.path.exists(surface_path):
        print(f"错误: 表面文件未找到于 {surface_path}")
        return None, None
    file_ext = os.path.splitext(surface_path)[1].lower()
    if file_ext in ['.pial', '.white', '.inflated', '.sphere', '.orig', '.smoothwm']:
        try:
            vertices, faces = nib.freesurfer.io.read_geometry(surface_path)
            print(f"使用 nibabel 加载了 {len(vertices)} 个顶点 (原生格式, 假定为 RAS)。")
            return vertices, faces
        except Exception as e:
            print(f"使用 nibabel 加载 FreeSurfer 表面 {surface_path} 出错: {e}")
            return None, None
    elif file_ext == '.stl':
        print("信息: 检测到 STL 文件。假定其顶点位于 LPS 坐标空间。")
        print("      将执行 LPS -> RAS 的转换 (x'=-x, y'=-y, z'=z)。")
        try:
            mesh_obj = trimesh.load_mesh(surface_path)
            if isinstance(mesh_obj, trimesh.Scene):
                if len(mesh_obj.geometry) == 1:
                    mesh_obj = list(mesh_obj.geometry.values())[0]
                else:
                    print(f"警告: STL 场景包含多个几何体。将它们合并。")
                    mesh_obj = trimesh.util.concatenate(list(mesh_obj.geometry.values()))
            if not isinstance(mesh_obj, trimesh.Trimesh):
                 raise TypeError(f"加载的对象不是 Trimesh 网格: {type(mesh_obj)}")
            vertices_lps = mesh_obj.vertices
            faces = mesh_obj.faces
            print(f"使用 trimesh 从 STL 加载了 {len(vertices_lps)} 个顶点 (LPS)。")
            print("      正在将顶点从 LPS 转换为 RAS...")
            vertices_ras = vertices_lps.copy()
            vertices_ras[:, 0] = -vertices_lps[:, 0]; vertices_ras[:, 1] = -vertices_lps[:, 1]
            print(f"      转换完成。现在顶点为 RAS 坐标系。")
            return vertices_ras, faces
        except Exception as e:
            print(f"处理 STL 文件 {surface_path} (加载或转换) 出错: {e}")
            return None, None
    else:
        print(f"警告: 不支持的表面文件格式 '{file_ext}'。")
        return None, None

# create_label_excluding_value_simple 函数 ... (与您提供的原始脚本完全一致) ...
def create_label_excluding_value_simple(surface_file_path, mgz_file_path, output_label_path,
                                        value_to_exclude):
    surface_vertices_ras, _ = read_surface(surface_file_path)
    if surface_vertices_ras is None: return False
    n_vertices = len(surface_vertices_ras)
    print(f"加载 MGZ 分割文件: {mgz_file_path}")
    if not os.path.exists(mgz_file_path): print(f"错误: MGZ 文件未找到于 {mgz_file_path}"); return False
    try:
        mgz_img = nib.load(mgz_file_path)
        mgz_data = mgz_img.get_fdata()
        mgz_affine_vox_to_ras = mgz_img.affine
        inv_mgz_affine_ras_to_vox = np.linalg.inv(mgz_affine_vox_to_ras)
        dims = mgz_data.shape
        print(f"MGZ 数据形状: {dims}, 数据类型: {mgz_data.dtype}")
    except Exception as e: print(f"加载 MGZ 文件 {mgz_file_path} 出错: {e}"); return False
    print("转换表面顶点 (RAS) 到 MGZ 体素坐标...")
    vertices_ras_homogeneous = np.hstack((surface_vertices_ras, np.ones((n_vertices, 1))))
    voxel_coords_homogeneous = inv_mgz_affine_ras_to_vox @ vertices_ras_homogeneous.T
    voxel_coords = voxel_coords_homogeneous[:3, :].T
    print("为所有顶点采样体素标签 (最近邻)...")
    voxel_indices = np.round(voxel_coords).astype(int)
    voxel_indices[:, 0] = np.clip(voxel_indices[:, 0], 0, dims[0] - 1)
    voxel_indices[:, 1] = np.clip(voxel_indices[:, 1], 0, dims[1] - 1)
    voxel_indices[:, 2] = np.clip(voxel_indices[:, 2], 0, dims[2] - 1)
    try:
        vertex_labels = mgz_data[voxel_indices[:, 0], voxel_indices[:, 1], voxel_indices[:, 2]]
    except Exception as e: print(f"标签采样过程中出错: {e}"); return False
    print(f"筛选顶点: 保留标签不等于 {value_to_exclude} 的顶点...")
    try:
        keep_mask = (vertex_labels != value_to_exclude)
        kept_vertex_indices = np.where(keep_mask)[0]
    except Exception as e: print(f"筛选顶点时出错 (比较标签值): {e}"); return False
    num_kept_vertices = len(kept_vertex_indices); num_excluded = n_vertices - num_kept_vertices
    print(f"排除了 {num_excluded} 个顶点 (标签为 {value_to_exclude}), 保留了 {num_kept_vertices} 个顶点。")
    if num_kept_vertices == 0: print(f"警告: 没有顶点被保留下来。"); print("  将写入一个空的 label 文件。")
    print(f"写入 label 文件到: {output_label_path}")
    kept_coords_ras = surface_vertices_ras[kept_vertex_indices]
    try:
        os.makedirs(os.path.dirname(output_label_path), exist_ok=True)
        with open(output_label_path, 'w') as f:
            f.write("#!ascii label, generated by script\n"); f.write(f"{num_kept_vertices}\n")
            for i in range(num_kept_vertices):
                vertex_index = kept_vertex_indices[i]; coords = kept_coords_ras[i]
                f.write(f"{vertex_index}  {coords[0]:.6f}  {coords[1]:.6f}  {coords[2]:.6f}  0.000000\n")
        print("Label 文件成功创建。")
        return True
    except Exception as e: print(f"写入 label 文件 {output_label_path} 出错: {e}"); return False

# ===================== 主程序入口 =====================
if __name__ == "__main__":
    # --- 1. 设置命令行参数解析 ---
    parser = argparse.ArgumentParser(description="从表面文件和 MGZ 分割中生成 FreeSurfer 标签文件，排除特定标签值 (模拟原始脚本的表面选择逻辑)。")
    # 修改参数以匹配原始脚本的需要
    parser.add_argument('--subjects_dir', required=True, type=str,
                        help="FreeSurfer SUBJECTS_DIR 路径。")
    parser.add_argument('--subject_id', required=True, type=str,
                        help="受试者 ID。")
    parser.add_argument('--hemi', required=True, choices=['lh', 'rh'],
                        help="要处理的半球 (lh 或 rh)。")
    parser.add_argument('--seg', required=True, type=str,
                        help="输入的 MGZ 分割文件路径。")
    parser.add_argument('--out', required=True, type=str,
                        help="输出的 FreeSurfer .label 文件路径。")
    parser.add_argument('--exclude_value', required=True, type=int,
                        help="需要从标签文件中排除的 MGZ 体素标签值。")
    # 添加一个可选参数来指定 fallback STL 文件名 (如果需要的话)
    parser.add_argument('--fallback_stl_name', type=str, default=None,
                        help="如果找不到原生表面，回退使用的 STL 文件名 (位于 surf/ 目录下)。")

    args = parser.parse_args()

    # --- 2. 打印配置信息 ---
    print("\n--- [ 配置信息 ] ---")
    print(f"Subjects Dir (--subjects_dir): {args.subjects_dir}")
    print(f"Subject ID (--subject_id):     {args.subject_id}")
    print(f"Hemisphere (--hemi):         {args.hemi}")
    print(f"分割文件 (--seg):            {args.seg}")
    print(f"输出标签文件 (--out):        {args.out}")
    print(f"排除值 (--exclude_value):    {args.exclude_value}")
    if args.fallback_stl_name:
        print(f"回退 STL 文件名 (--fallback_stl_name): {args.fallback_stl_name}")

    # --- 3. 实现原始脚本中的表面选择逻辑 ---
    print("\n--- [ 查找输入表面文件 (优先 .pial > .white > fallback STL) ] ---")
    fs_surf_dir = os.path.join(args.subjects_dir, args.subject_id, "surf")
    native_surface_file_pial = os.path.join(fs_surf_dir, f"{args.hemi}.pial")
    native_surface_file_white = os.path.join(fs_surf_dir, f"{args.hemi}.white")
    surface_to_use = None

    if os.path.exists(native_surface_file_pial):
        surface_to_use = native_surface_file_pial
        print(f"找到并使用原生表面 (RAS): {surface_to_use}")
    elif os.path.exists(native_surface_file_white):
        surface_to_use = native_surface_file_white
        print(f"找到并使用原生表面 (RAS): {surface_to_use}")
    else:
        print("未找到原生 FreeSurfer 表面 (.pial or .white)。")
        # 检查是否提供了 fallback STL 文件名
        if args.fallback_stl_name:
            stl_surface_file = os.path.join(fs_surf_dir, args.fallback_stl_name)
            if os.path.exists(stl_surface_file):
                 print(f"回退到使用指定的 STL 文件 (LPS): {stl_surface_file}")
                 surface_to_use = stl_surface_file
            else:
                 print(f"错误: 指定的回退 STL 文件未找到: {stl_surface_file}")
                 surface_to_use = None
        else:
             print("错误: 未提供回退 STL 文件名，且找不到原生表面。")
             surface_to_use = None

    # --- 4. 调用核心处理函数 (如果找到了表面) ---
    if surface_to_use:
        print(f"\n--- 创建 Label 文件: 使用表面 '{os.path.basename(surface_to_use)}', 排除值 {args.exclude_value} ---")
        success = create_label_excluding_value_simple(
            surface_file_path=surface_to_use,          # 使用自动选择的表面
            mgz_file_path=args.seg,
            output_label_path=args.out,
            value_to_exclude=args.exclude_value
        )
        # --- 5. 报告最终结果 ---
        if success:
            print("\n[完成] 处理成功完成。")
        else:
            print("\n[失败] 处理过程中出现错误。")
            sys.exit(1)
    else:
        print("\n[失败] 没有有效的表面文件可供处理，脚本终止。")
        sys.exit(1)